name: "build"
on: [push, pull_request]
jobs:
  launch-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Run the notebooks
        run: |
          cd notebooks
          sudo apt-get install openjdk-8-jdk-headless -qq > /dev/null
          wget -q https://archive.apache.org/dist/spark/spark-3.2.1/spark-3.2.1-bin-hadoop2.7.tgz
          
          sudo mkdir -p /content
          tar xf spark-3.2.1-bin-hadoop2.7.tgz
          sudo mv spark-3.2.1-bin-hadoop2.7 /content

          pip install -r requirements.txt > /dev/null
          for f in *.ipynb; 
            do echo "Processing $f file...";
            jupyter nbconvert --execute --to notebook --inplace $f
            jupyter nbconvert --to script $f
            extension="${f##*.}"
            filename="${f%.*}"
            ipython $filename.py
          done
          ls -las
